trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob
  - job: SecondJob
    steps:
    - bash: echo Build SecondJob
    - bash: echo $(PipelineLevelVariable)
- stage: DevDeploy
  variables:
    environment: Dev
  jobs:
  - job: DevDeployJob
    steps:
    - bash: echo $(environment)DeployJob
- stage: QADeploy
  dependsOn: Build
  jobs:
  - job: QADeployJob
    steps:
    - bash: echo QADeployJob
- stage: ProdDeploy
  variables:
    environment: Prod
  dependsOn:
  - Build
  - Devdeploy
  - QADeploy
  jobs:
  - job: ProdDeployJob
    steps:
    - bash: echo DevdeployJob
    - bash: echo $(environment)DeployJob

